=== ajoby2003/cse445_a4/NationalParks.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="NationalParks">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="NationalPark" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="Name" type="xsd:string"/>
              <xsd:element name="Phone" type="xsd:string" maxOccurs="unbounded"/>
              <xsd:element name="Address">
                <xsd:complexType>
                  <xsd:sequence>
                    <xsd:element name="Number" type="xsd:string"/>
                    <xsd:element name="Street" type="xsd:string"/>
                    <xsd:element name="City" type="xsd:string"/>
                    <xsd:element name="State" type="xsd:string"/>
                    <xsd:element name="Zip" type="xsd:string"/>
                  </xsd:sequence>
                  <xsd:attribute name="NearstAirport" type="xsd:string" use="required"/>
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="Rating" type="xsd:decimal" use="optional"/>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== ajoby2003/cse445_a4/NationalParks.xml
<?xml version="1.0" encoding="UTF-8"?>
<NationalParks xmlns="http://venus.sod.asu.edu/WSRepository/xml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://ajoby2003.github.io/cse445_a4/NationalParks.xsd">
  <NationalPark Rating="4.9">
    <Name>Grand Canyon</Name>
    <Phone>928-638-7496</Phone>
    <Phone>888-297-2757</Phone>
    <Phone>866-499-2574</Phone>
    <Address NearestAirport="FlagStaff">
      <Number>8</Number>
      <Street>S Entrance Road</Street>
      <City>Grand Canyon</City>
      <State>AZ</State>
      <Zip>86023</Zip>
    </Address>
  </NationalPark>
  
  <NationalPark>
    <Name>Coronado National Forest</Name>
    <Phone>520-388-8300</Phone>
    <Address NearestAirport="Tucson International Airport">
      <Number>300</Number>
      <Street>W Congress St.</Street>
      <City>Tucson</City>
      <State>AZ</State>
      <Zip>85701</Zip>
    </Address>
  </NationalPark>
  
  <NationalPark Rating="4.8">
    <Name>Rocky Mountain National Park</Name>
    <Phone>970-586-1206</Phone>
    <Address NearestAirport="Denver International Airport">
      <Number>1000</Number>
      <Street>U.S. Highway 36</Street>
      <City>Estes Park</City>
      <State>CO</State>
      <Zip>80517</Zip>
    </Address>
  </NationalPark>
  
  <NationalPark Rating="4.9">
    <Name>Acadia National Park</Name>
    <Phone>207-288-3338</Phone>
    <Address NearestAirport="Bangor International Airport">
      <Number>20</Number>
      <Street>McFarland Hill Dr</Street>
      <City>Bar Harbor</City>
      <State>ME</State>
      <Zip>04609</Zip>
    </Address>
  </NationalPark>
  
  <NationalPark Rating="4.8">
    <Name>Zion National Park</Name>
    <Phone>435-772-3256</Phone>
    <Phone>435-772-7700</Phone>
    <Address NearestAirport="Harry Reid International Airport">
      <Number>1</Number>
      <Street>Zion Park Blvd</Street>
      <City>Springdale</City>
      <State>UT</State>
      <Zip>84767</Zip>
    </Address>
  </NationalPark>
  
  <NationalPark Rating="4.9">
    <Name>Great Smoky Mountains National Park</Name>
    <Phone>865-436-1200</Phone>
    <Address NearestAirport="McGhee Tyson Airport">
      <Number>107</Number>
      <Street>Park Headquarters Rd</Street>
      <City>Gatlinburg</City>
      <State>TN</State>
      <Zip>37738</Zip>
    </Address>
  </NationalPark>
  
  <NationalPark Rating="4.8">
    <Name>Cuyahoga Valley National Park</Name>
    <Phone>440-546-5918</Phone>
    <Address NearestAirport="Cleveland Hopkins International Airport">
      <Number>15610</Number>
      <Street>Vaughn Rd</Street>
      <City>Brecksville</City>
      <State>OH</State>
      <Zip>44141</Zip>
    </Address>
  </NationalPark>
  
  <NationalPark Rating="4.9">
    <Name>Badlands national park</Name>
    <Phone>605-433-5361</Phone>
    <Address NearestAirport="Rapid City Regional Airport">
      <Number>25216</Number>
      <Street>Ben Reifel Rd</Street>
      <City>Interior</City>
      <State>SD</State>
      <Zip>57750</Zip>
    </Address>
  </NationalPark>
  
  <NationalPark Rating="4.8">
    <Name>Saguaro National Park</Name>
    <Phone>520-733-5153</Phone>
    <Address NearestAirport="Tucson International Airport">
      <Number>3693</Number>
      <Street>S Old Spanish Trail</Street>
      <City>Tucson</City>
      <State>AZ</State>
      <Zip>85730</Zip>
    </Address>
  </NationalPark>
  
  <NationalPark Rating="4.8">
    <Name>Capitol Reef National Park</Name>
    <Phone>435-425-3791</Phone>
    <Address NearestAirport="Salt Lake City International Airport">
      <Number>52</Number>
      <Street>West Headquarters Drive</Street>
      <City>Torrey</City>
      <State>UT</State>
      <Zip>84775</Zip>
    </Address>
  </NationalPark>
  
  <NationalPark Rating="4.7">
    <Name>Great Basin National Park</Name>
    <Phone>775-234-7331</Phone>
    <Address NearestAirport="Harry Reid International Airport">
      <Number>100</Number>
      <Street>Great Basin National Park</Street>
      <City>Baker</City>
      <State>NV</State>
      <Zip>89311</Zip>
    </Address>
  </NationalPark>
  
</NationalParks>
